lr: 1.0e-3
batch_size: 16

model_args:
  in_channels: 2
  num_hid: 32
  num_heads: 4
  tformer_n_layers: 1
  eps: 0.5
  lmbd: 0.01
  weight_beta: 0.2
  weight_delta: 0.2
  hand_cluster: True
  gesture_extractor_cls: signbert.model.GestureExtractorSpatTemp.GestureExtractor
  gesture_extractor_args:
    in_channels: 2
    inter_channels: [32, 32]
    fc_unit: 32
    layout: mediapipe_hand
    strategy: spatial
    pad: 1