lr: 0.005265204739364684
batch_size: 16
normalize: true
manotorch: true

dataset_args:
  K: 3
  R: 0.2
  m: 8
  max_disturbance: 3.297473527420909

model_args:
  in_channels: 2
  num_hid: 32
  num_heads: 4
  tformer_n_layers: 1
  tformer_dropout: 0.25
  eps: 0.5
  lmbd: 0.01
  weight_beta: 228.189682060746
  weight_delta: 162.78198230721895
  hand_cluster: False
  n_pca_components: 14
  gesture_extractor_cls: signbert.model.GestureExtractor.GestureExtractor
  gesture_extractor_args:
    in_channels: 2
    num_hid: 32
    dropout: 0.25
  use_onecycle_lr: true
  pct_start: 0.3
  weight_decay: 3.293551183580393e-05
  total_steps: 600