lr: 1.0e-3
batch_size: 16
normalize: true
manotorch: true

model_args:
  in_channels: 2
  num_hid: 32
  num_heads: 4
  tformer_n_layers: 1
  tformer_dropout: 0.25
  eps: 0.5
  lmbd: 0.01
  weight_beta: 1.5
  weight_delta: 1.5
  hand_cluster: False
  n_pca_components: 11
  gesture_extractor_cls: signbert.model.GestureExtractor.GestureExtractor
  gesture_extractor_args:
    in_channels: 2
    num_hid: 32
    dropout: 0.25