lr: 1.0e-3
batch_size: 16
accumulate_grad_batches: 1
normalize: true
manotorch: true

model_args:
  in_channels: 2
  num_hid: 128
  num_heads: 4
  tformer_n_layers: 4
  tformer_dropout: 0.25
  eps: 0.5
  lmbd: 0.01
  weight_beta: 200.
  weight_delta: 200.
  hand_cluster: True
  n_pca_components: 11
  gesture_extractor_cls: signbert.model.GestureExtractorSpatTemp.GestureExtractor
  gesture_extractor_args:
    in_channels: 2
    inter_channels: [64, 128]
    fc_unit: 128
    layout: mediapipe_hand
    strategy: spatial
    pad: 1